# Configuration file for IFD Handler 2.0 drivers
# FRIENDLYNAME: Any name
# DEVICENAME: Do not set
# LIBPATH: Location of the driver library for your reader
# CHANNELID:
#             0x000001 - COM1 (/dev/ttyS0)
#             0x000002 - COM2 (/dev/ttyS1)
#             0x000003 - COM3 (/dev/ttyS2)
#             0x000004 - COM4 (/dev/ttyS3)
#             0x200000 - First USB-serial device (/dev/ttyUSB0)
#             0x200001 - Second USB-serial device (/dev/ttyUSB1)
#             0x200002 - Third USB-serial device (/dev/ttyUSB2)
#             0x200003 - Fourth USB-serial device (/dev/ttyUSB3)
#

# Towitoko Chipdrive Micro (COM1)
FRIENDLYNAME	"Towitoko Chipdrive Micro"
LIBPATH		/usr/local/towitoko/lib/libtowitoko.so.2.0.0
CHANNELID	0x000001

# Note: Use the full path on LIBPATH.
