#!/bin/sh
#
# postinst configure most-recently-configured-version 
# old-postinst abort-upgrade new-version 
# conflictor's-postinst abort-remove in-favour package new-version 
# deconfigured's-postinst abort-deconfigure in-favour failed-install-package version removing conflicting-package version 
#

set -e

cfgdir=/etc/reader.conf.d
cfg=$cfgdir/libtowitoko2
lib=/usr/lib/libtowitoko.so.2.0.0
pcsclite_dir=/usr/lib/pcsc

if [ "$1" = "configure" ]; then

  # Source debconf library.
  . /usr/share/debconf/confmodule

  db_get 'libtowitoko2/port' || true
  SERIAL_PORT="$RET"

  # First make sure the cfgdir exists
  if [ ! -d $cfgdir ]; then
    mkdir -p $cfgdir
  fi

  echo "# Towitoko chipdrive reader with serial communication" > $cfg
  echo "# This file has been generated. Do not change it manually." >> $cfg
  echo "# Instead run dpkg-reconfigure libtowitoko2." >> $cfg
  echo "# DEVICENAME must not be set." >> $cfg
  echo "# CHANNELID must be: " >> $cfg
  echo "#   - 0x000001: COM1 (/dev/ttyS0)" >> $cfg
  echo "#   - 0x000002: COM2 (/dev/ttyS1)" >> $cfg
  echo "#   - 0x000003: COM3 (/dev/ttyS2)" >> $cfg
  echo "#   - 0x000004: COM4 (/dev/ttyS3)" >> $cfg
  echo "#   - 0x200000: First USB-serial device (/dev/ttyUSB0)" >> $cfg
  echo "#   - 0x200001: Second USB-serial device (/dev/ttyUSB1)" >> $cfg
  echo "#   - 0x200002: Third USB-serial device (/dev/ttyUSB2)" >> $cfg
  echo "#   - 0x200003: Fourth USB-serial device (/dev/ttyUSB3)" >> $cfg

  echo "FRIENDLYNAME      \"Towitoko Chipdrive Reader\"" >> $cfg

  case "$SERIAL_PORT" in
    ttyS0)
      echo "CHANNELID         0x000001" >> $cfg
      ;;
    ttyS1)
      echo "CHANNELID         0x000002" >> $cfg
      ;;
    ttyS2)
      echo "CHANNELID         0x000003" >> $cfg
      ;;
    ttyS3)
      echo "CHANNELID         0x000004" >> $cfg
      ;;
    USB)
      echo "CHANNELID         0x200000" >> $cfg
      ;;
    ttyUSB0)
      echo "CHANNELID         0x200000" >> $cfg
      ;;
    ttyUSB1)
      echo "CHANNELID         0x200001" >> $cfg
      ;;
    ttyUSB2)
      echo "CHANNELID         0x200002" >> $cfg
      ;;
    ttyUSB3)
      echo "CHANNELID         0x200003" >> $cfg
      ;;
    *)
      echo "Error: serial port unknown ($SERIAL_PORT)"
      ;;
  esac

  echo "LIBPATH           $lib" >> $cfg

  # regenerate /etc/reader.conf if update-reader.conf is available
  if [ -x /usr/sbin/update-reader.conf ]; then
    /usr/sbin/update-reader.conf || true
  fi

  # ensure that /usr/lib/pcsc/drivers directory exists otherwise pcscd will exit
  mkdir -p $pcsclite_dir/drivers

  db_stop

  if [ -x /etc/init.d/pcscd ]; then
    invoke-rc.d pcscd restart 3>/dev/null
  fi
fi

#DEBHELPER#
